### ISSUE TITLE
Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by acs-ferreira** [yiisoft/yii2-redis#108]
### What's expected?
Connection to redis server issuing AUTH command
### What do you get instead?
```
yii\db\Exception: Redis error: ERR Client sent AUTH, but no password is set
Redis command was: AUTH goodpassword in /vendor/yiisoft/yii2-redis/Connection.php:675

Stack trace:
#0 /vendor/yiisoft/yii2-redis/Connection.php(652): yii\redis\Connection->parseResponse('AUTH goodpasswo...')
#1 /vendor/yiisoft/yii2-redis/Connection.php(536): yii\redis\Connection->executeCommand('AUTH', Array)
#2 /vendor/yiisoft/yii2-redis/Connection.php(641): yii\redis\Connection->open()
#3 /vendor/yiisoft/yii2-redis/Cache.php(102): yii\redis\Connection->executeCommand('GET', Array)
#4 /vendor/yiisoft/yii2/caching/Cache.php(114): yii\redis\Cache->getValue('humhub310a82fd7...')
#5 /humhub/components/bootstrap/ModuleAutoLoader.php(26): yii\caching\Cache->get('humhub310a82fd7...')
#6 /vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#7 /vendor/yiisoft/yii2/base/Application.php(272): yii\base\Application->bootstrap()
#8 /vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#9 /humhub/components/console/Application.php(35): yii\console\Application->init()
#10 /vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
#11 /vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#12 /vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#13 /yii(28): yii\console\Application->__construct(Array)
#14 {main} Additional Information: Array ( ) 
```

### Additional info

```
'cache' => [
    'class' => 'yii\redis\Cache',
    'redis' => [
        'hostname' => '10.99.0.14',
        'port' => 6379,
        'database' => 5,
        'password' => 'goodpassword',
    ]
],
```

`requirepass` is set on `redis.conf`

![image](https://cloud.githubusercontent.com/assets/12234510/26037958/7a6f4ff6-38fe-11e7-8875-0c3f86751dec.png)

Testing with `redis-cli`

```
$redis-cli
127.0.0.1:6379> PING
(error) NOAUTH Authentication required.
127.0.0.1:6379> AUTH badpassword
(error) ERR invalid password
127.0.0.1:6379> AUTH goodpassword
OK
127.0.0.1:6379> PING
PONG
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.2
| PHP version      | 7.1.5
| Operating system | Ubuntu 16.04
| Redis | 3.2.8

**Comment by cebe** [comment]
are you sure you are connecting to the same redis instance? host in the config is 10.99.0.14 but redis-cli connects to 127.0.0.1

**Comment by acs-ferreira** [comment]
Yes, redis is binding on both `10.99.0.14` and `127.0.0.1`

Connecting from a "remote" host on the same LAN (`10.99.0.11` to `10.99.0.14`), issuing `redis-cli` commands on the server itself, so `127.0.0.1`.

**Comment by acs-ferreira** [comment]
But just to be sure:

```
root@srv:~# redis-cli -h 10.99.0.14
10.99.0.14:6379> AUTH badpass
(error) ERR invalid password
10.99.0.14:6379> AUTH Tgoodpassword
OK
10.99.0.14:6379> PING
PONG
```

**Comment by cebe** [comment]
Is this a single redis server setup or are there master-slave replication, sentinel or some proxies involved?

**Comment by acs-ferreira** [comment]
Single server.
I was running 3.0.6 without no issues, this issue/warning has appeared after upgrading to 3.2.8.

**Comment by acs-ferreira** [comment]
Closing for now as rebuild the Redis server seem to have fixed this, so it seems it is not extension related.
